# Generated by Django 5.1.3 on 2025-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientType', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20)),
                ('distributionChannel', models.CharField(choices=[('HeadOffice', 'Head Office'), ('Broker', 'Broker'), ('Agent', 'Agent')], default='HeadOffice', max_length=20)),
                ('fullName', models.CharField(blank=True, max_length=100)),
                ('nationalId', models.CharField(blank=True, max_length=100)),
                ('corporateName', models.CharField(blank=True, max_length=100)),
                ('ubo', models.CharField(blank=True, max_length=100)),
                ('natureOfBusiness', models.CharField(blank=True, max_length=100)),
                ('brn', models.CharField(blank=True, max_length=100)),
                ('vat', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
