# Generated by Django 5.1.3 on 2025-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_kycdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='distributionChannel',
            field=models.CharField(choices=[('HeadOffice', 'Head Office'), ('Branch', 'Branch'), ('Agent', 'Agent')], default='HeadOffice', max_length=20),
        ),
    ]
