# Generated by Django 5.1.3 on 2025-11-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_update_to_distribution_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='distributionChannel_old',
            new_name='distributionChannel',
        ),
    ]
